###
POST http://localhost:4000/forgotPassword
content-type: application/json

{
    "email": "bhdnirmal99@gmail.com"
}

###

POST http://localhost:4000/login
content-type: application/json

{
    "username": "bhdnirmal99@gmail.com"
}

###